# Make program that takes two numbers as inputs and prints their sum, difference, product and division
a = int(input("Sum; Enter first number: "))
b = int(input("Sum;Enter second second: "))
print("The sum of", a, "and", b, "is:", a + b)
a = int(input("Difference; Enter first number: "))
b = int(input("Difference;Enter second second: "))
print("The difference of", a, "and", b, "is:", a - b)
a = int(input("Product; Enter first number: "))
b = int(input("Product; Enter second second: "))
print("The product of", a, "and", b, "is:", a * b)
a = int(input("Division; Enter first number: "))
b = int(input("Division; 10Enter second second: "))
print("The division of", a, "and", b, "is:", a / b)